[package]
name = "undaf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.12"
ron = "0.8.1"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.56"
